mindmap
	root((（一）马克思主义的创立))
		导论
			马克思主义理论具有整体性
				以事实为依据、以规律为对象，并以实践为检验标准
				马克思主义的发展是一个不断探索和掌握客观规律的过程
		人民的理论
			人民性是马克思主义的本质属性
				人民至上是马克思主义的政治立场
				马克思主义植根于人民，为了人民
				无产阶级解放与全人类解放一致
				反对私有制社会特别是资本主义社会的经济剥削和政治压迫
		实践的理论
			马克思主义是从实践中来、到实践中去
				在实践中接受检验，并随实践而不断发展
				直接服务于无产阶级和人民群众改造世界的实践活动
				实践观点是马克思主义首要的基本观点
		发展的理论
			马克思主义是不断发展的开放的学说
				与时俱进的理论品质
				指导社会主义事业发展的过程中不断丰富和发展
				形成新的理论成果如马克思主义中国化时代化理论成果
		基本特征
			科学性与革命性的统一
				马克思主义科学理论在指导伟大社会革命的过程中体现其特性
				革命性是内在品质
		当代价值
			观察当代世界变化的认识工具
			指引当代中国发展的行动指南
				中国共产党坚持马克思主义基本原理，推进马克思主义中国化时代化