mindmap
  root((第二节 事物的普遍联系和变化发展))
    联系和发展的普遍性
      事物的普遍联系
        定义
          恩格斯的观点
        特点
          客观性
          普遍性
            内部结构性
            事物间联系
            世界统一整体
          多样性
            直接与间接联系
            内部与外部联系
            本质与非本质联系
            必然与偶然联系
          条件性
            支持或制约作用
            条件可改变
            尊重客观规律
      事物的变化发展
        定义
          恩格斯的观点
        变化与发展
          变化
          发展
        新陈代谢
          新事物产生
          旧事物灭亡
          新事物不可战胜的原因
            适应环境
            否定旧事物
            保留合理因素
    对立统一规律是事物发展的根本规律
      矛盾的同一性和斗争性
        同一性
          定义
          作用
        斗争性
          定义
          作用
        关系
          相互依存
          相辅相成
      矛盾的普遍性和特殊性
        普遍性
          定义
        特殊性
          定义
        相互关系
          共性与个性
          绝对与相对
          认识方法
    量变质变规律和否定之否定规律
      量变质变规律
        量、质、度
        量变
        质变
        关系
          量变是质变的准备
          质变是量变的结果
          相互渗透
      否定之否定规律
        定义
        否定的内涵
        实质：扬弃
        两次否定三个阶段
        前进性与曲折性
    联系和发展的基本环节