mindmap
  root((第二节 真理与价值))
    实践与认识的统一
      具体的统一
        主观认识要与一定时间、地点、条件下的客观实践相符合
      历史的统一
        主观认识要同特定历史发展阶段的客观实践相符合
    真理与价值的关系
      把握规律、掌握真理
      追求意义、创造价值
    一、真理的客观性、绝对性和相对性
      真理的客观性
        真理是标志主观与客观相符合的哲学范畴
        真理的内容是对客观事物及其规律的正确反映
        真理的一元性
          在同一条件下对于特定的认识客体的真理性认识只有一个
      真理的绝对性和相对性
        真理的绝对性
          真理主客观统一的确定性和发展的无限性
        真理的相对性
          对客观事物及其本质和发展规律的正确认识总是有限度的、不完善的
        真理的绝对性和相对性的辩证统一
          绝对之中有相对，相对之中有绝对
    二、真理与谬误
      谬误的定义
        同客观事物及其发展规律相违背的认识
      真理与谬误的对立统一
        相互对立
          在确定的对象和范围内，真理与谬误的对立是绝对的
        相互转化
          在一定条件下能够相互转化
    三、真理的检验标准
      哲学史上关于真理标准问题的争论
        不同的观点
          圣人或权威的意见为标准
          自己的观念、意见为标准
          概念是否清楚明白为标准
      实践是检验真理的唯一标准
        真理的本性决定实践作为检验标准
        实践的特点决定实践作为检验标准
      实践标准的确定性与不确定性
        确定性
          实践作为检验真理标准的唯一性、归根到底性、最终性
        不确定性
          实践作为检验真理标准的条件性
    四、真理与价值的辩证统
      通过实践改造世界
      存在主观符合客观的真理问题
      存在按照主体的需要认识世界和改造世界的价值问题