mindmap
  root((第一节 商品经济和价值规律))
    商品经济的形成和发展
      资本主义生产关系与商品经济的关系
      商品经济的发展阶段
        简单商品经济
        发达商品经济
      商品经济产生的历史条件
        社会分工
        生产资料和劳动产品属于不同的所有者
    商品的二因素和生产商品的劳动的二重性
      商品的二因素
        使用价值
        价值
      生产商品的劳动的二重性
        具体劳动
        抽象劳动
    商品价值量的决定
      决定商品价值量的因素
        劳动时间
        社会必要劳动时间
      简单劳动与复杂劳动
    价值形式的发展与货币的产生
      价值形式的发展阶段
        简单或偶然的价值形式
        总和的或扩大的价值形式
        一般价值形式
        货币形式
      货币的职能
    价值规律及其作用
      价值规律的内容
      价值规律的作用
        调节生产资料和劳动力分配
        刺激社会生产力发展
        调节社会收入分配
      价值规律的消极后果
        社会资源浪费
        阻碍技术进步
        导致收入两极分化
    以私有制为基础的商品经济的基本矛盾
      私人劳动和社会劳动的矛盾
      商品经济的本质及发展过程
      商品经济其他一切矛盾的基础
      商品生产者的命运
    深刻认识马克思劳动价值论的当代价值