mindmap
  root((第三节 资本主义上层建筑))
    政治上层建筑
      资本主义政治制度及其本质
        资本主义国家的职能和本质
          对内职能
            政治统治
            社会管理
          对外职能
            国际交往
            维护国家安全及利益
        资本主义民主制度及其本质
          法律制度
          政权组织形式
          选举制度
          政党制度
      资本主义意识形态及其本质
        形成
          反封建专制主义
          反宗教神学
        核心思想
          私有制神圣不可侵犯观念
          个人主义价值观