mindmap
  root((第三节 在实践中探索社会主义的发展规律))
    民主与自我革命
      第一个答案：民主
        人民监督政府
      第二个答案：自我革命
        党的自我净化、完善、革新、提高
    中国特色社会主义新时代
      科学社会主义基本原则与当代中国实际结合
      实践创新与理论创新良性互动
    社会主义建设过程的长期性
      生产力发展状况制约
      经济基础和上层建筑发展状况制约
      国际环境严峻挑战
      马克思主义执政党对社会主义建设规律的认识
    社会主义发展道路的多样性
      多样性的原因
        各国国情差异
        历史文化传统
        时代和实践发展
      探索适合本国国情的道路
        科学态度对待马克思主义
        走自己的路
        吸收人类优秀文明成果
    社会在实践中开拓前进
      社会主义是亿万人民群众的伟大实践
      社会主义实践不断探索的过程