mindmap
  root((第一节 展望未来共产主义新社会))
    共产主义的含义
      意义1:共产主义思想体系
      意义2:共产主义运动
      意义3:共产主义社会
    预见未来社会的方法论原则
      科学立场观点方法的重要性
      揭示人类社会发展一般规律
        作为正确预见未来的依据
      剖析资本主义旧世界
        发现新世界的特点
      社会主义社会发展中的启示
        对共产主义社会的新认识
      不对细节作具体描绘
        只指出发展方向、原则和基本特征
    共产主义社会的基本特征
      物质财富极大丰富
        产品按需分配
      人民精神境界极大提高
      每个人自由而全面发展