mindmap
	root((一、什么是马克思主义))
		马克思主义的定义
			科学理论体系
				关于自然、社会和人类思维发展一般规律
				社会主义代替资本主义
				无产阶级解放与全人类解放
				自由而全面的发展
				行动指南
		理论体系组成
			马克思主义哲学
			马克思主义政治经济学
			科学社会主义
		马克思主义基本原理
			立场观点方法的集中概括
			普遍真理性的理论
			科学性与革命性的统一
			学习和把握
				基本立场
					无产阶级解放
					全人类解放
					人的自由全面发展
					以人民为中心
				基本观点
					世界物质统一
					事物矛盾运动
					实践与认识辩证关系
					社会存在决定意识
					人与自然和谐共生
					社会基本矛盾
					自由全面发展
					世界历史
					阶级斗争
					人民群众创造历史
					劳动价值论
					剩余价值
					资本主义本质
					垄断资本主义
					社会主义替代
					社会主义革命
					无产阶级政党建设
					社会主义社会特征
					共产主义理想
				基本方法
					实事求是
					辩证分析
					社会基本矛盾分析
					历史分析
					阶级分析
					群众路线