mindmap
	root((（二）马克思主义的发展))
		马克思主义作为精神动力
			信仰与国家力量
				中国革命、建设、改革的精神动力
					习近平的论述
						党员、干部的理想信念
						人民群众的精神状态
			党的初心和使命
				为中国人民谋幸福，为中华民族谋复兴
					激励党不断前进的动力
						与人民同呼吸、共命运
						奋斗姿态
		马克思主义作为行动指南
			指导实践的威力
				应对重大挑战、抵御风险、克服阻力、解决矛盾
					科学理论指导的重要性
						中国走向繁荣富强
						综合国力和生活水平提升
						全面建设社会主义现代化国家
			理论创新与实践探索
				坚持与发展马克思主义的统一
					推进实践基础上的理论创新
		引领人类社会进步的科学真理
			资本主义基本矛盾的存在
				西方金融危机和社会危机
					马克思主义著作热销
						《资本论》等著作的影响
						关于马克思主义的研究热潮
			社会主义代替资本主义的历史趋势
				当今时代的问题
					贫困、生态恶化、恐怖主义等问题
						马克思主义中的智慧
							探寻人类社会奥秘
							揭示历史规律
							指明前进方向