mindmap
	root((第一节 人类社会的存在与发展))
		一、社会存在与社会意识
			（一）两种根本对立的历史观
				唯物史观
				唯心史观
			（二）社会存在
				自然地理环境
				人口因素
				物质生产方式
			（三）社会意识
				个体意识
				群体意识
				社会心理
				社会意识形式
				意识形态
				非意识形态
			（四）社会存在和社会意识的辩证关系
				社会存在决定社会意识
				社会意识反作用于社会存在
				社会意识的相对独立性
			（五）社会存在和社会意识辩证关系原理的重要意义
		二、社会基本矛盾及其运动规律
			（一）生产力与生产关系的矛盾运动及其规律
				生产力的要素
				生产关系的基本类型
				生产力与生产关系的相互作用
			（二）经济基础与上层建筑的矛盾运动及其规律
				经济基础的内涵
				上层建筑的构成
				经济基础与上层建筑的相互作用
				经济基础和上层建筑之间的内在联系
		三、人类普遍交往与世界历史的形成发展
			（一）交往及其作用
				促进生产力的发展
				促进社会关系的进步
				促进文化的发展与传播
				促进人的全面发展
			（二）世界历史的形成和发展
				世界历史的基本特征
				世界历史的形成与发展为共产主义的实现提供了条件和路径
		四、社会进步与社会形态更替
			（一）社会进步与人的发展
				社会进步的表现
				社会进步促进人的发展
				社会进步推动人类解放
			（二）社会形态的内涵
				社会形态的定义
				社会形态的组成
			（三）社会形态更替的统一性和多样性
				社会形态更替的统一性
				社会形态更替的多样性
			（四）社会形态更替中的必然性与选择性
				社会形态更替的必然性
				社会形态更替的选择性
		五、文明及其多样性
			（一）文明及其演进
				文明的定义
				文明发展的过程